"""empty message

Revision ID: a88b8b2a83c5
Revises: None
Create Date: 2018-05-19 21:26:02.940623

"""

# revision identifiers, used by Alembic.
revision = 'a88b8b2a83c5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('lighting_condition', sa.String(length=40), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouses')
    # ### end Alembic commands ###
